import type { ImageMapping } from '@/types/app';

export const DEFAULT_BANK_IMAGE = '/images/bank/bank-default.svg';

export const MAPPING_BANK_FULL_IMAGE: ImageMapping = {
  abbank: '/images/bank/full/abbank.webp',
  acb: '/images/bank/full/acb.webp',
  agribank: '/images/bank/full/agribank.webp',
  bacabank: '/images/bank/full/bacabank.webp',
  baoviet: '/images/bank/full/baoviet.webp',
  baovietbank: '/images/bank/full/baovietbank.webp',
  bidv: '/images/bank/full/bidv.webp',
  bvb: '/images/bank/full/bvb.webp',
  cb: '/images/bank/full/cb.webp',
  donga: '/images/bank/full/donga.webp',
  dab: '/images/bank/full/donga.webp',
  vikki: '/images/bank/full/donga.webp',
  vikkibank: '/images/bank/full/donga.webp',
  eab: '/images/bank/full/eab.webp',
  eib: '/images/bank/full/eib.webp',
  eximbank: '/images/bank/full/eximbank.webp',
  gpbank: '/images/bank/full/gpbank.webp',
  hdb: '/images/bank/full/hdb.webp',
  hdbank: '/images/bank/full/hdbank.webp',
  hsbc: '/images/bank/full/hsbc.webp',
  ivb: '/images/bank/full/ivb.webp',
  klb: '/images/bank/full/klb.webp',
  lpb: '/images/bank/full/lpb.webp',
  maritimebank: '/images/bank/full/maritimebank.webp',
  mb: '/images/bank/full/mb.webp',
  mbbank: '/images/bank/full/mbbank.webp',
  msb: '/images/bank/full/msb.webp',
  nab: '/images/bank/full/nab.webp',
  namabank: '/images/bank/full/namabank.webp',
  ncb: '/images/bank/full/ncb.webp',
  ocb: '/images/bank/full/ocb.webp',
  oceb: '/images/bank/full/oceb.webp',
  pgb: '/images/bank/full/pgb.webp',
  pgbank: '/images/bank/full/pgb.webp',
  pvcb: '/images/bank/full/pvcombank.webp',
  pvcombank: '/images/bank/full/pvcombank.webp',
  sab: '/images/bank/full/sacombank.webp',
  sacombank: '/images/bank/full/sacombank.webp',
  scb: '/images/bank/full/scb.webp',
  scbl: '/images/bank/full/scbl.webp',
  seab: '/images/bank/full/seab.webp',
  sgb: '/images/bank/full/sgb.webp',
  shb: '/images/bank/full/shb.webp',
  shbvn: '/images/bank/full/shbvn.webp',
  techcombank: '/images/bank/full/techcombank.webp',
  tcb: '/images/bank/full/techcombank.webp',
  tpbank: '/images/bank/full/tpbank.webp',
  vab: '/images/bank/full/vab.webp',
  vba: '/images/bank/full/agribank.webp',
  vcb: '/images/bank/full/vcb.webp',
  vccb: '/images/bank/full/vietcapital.webp',
  vib: '/images/bank/full/vibbank.webp',
  vietbank: '/images/bank/full/vietbank.webp',
  vietcapital: '/images/bank/full/vietcapital.webp',
  bvbank: '/images/bank/full/vietcapital.webp',
  vietinbank: '/images/bank/full/vietinbank.webp',
  vncb: '/images/bank/full/vncb.webp',
  vpb: '/images/bank/full/vpbank.webp',
  vpbank: '/images/bank/full/vpbank.webp',
  vtb: '/images/bank/full/vietinbank.webp',
  wb: '/images/bank/full/wb.webp',
};
