export enum GameTypeEnum {
  Hot = 'hot',
  NoHu = 'nohu',
}

export enum TopWinnerEnum {
  Day = 'day',
  Week = 'week',
  Month = 'month',
}

export enum GameCategoryEnum {
  All = 'all',
  CardGame = 'game_cards',
  Slots = 'slots',
  NoHu = 'nohu',
  Fishing = 'fishing',
  TableGame = 'tables_ingames',
  NumberGame = 'lottery',
  Lottery = 'lo_de',
  Keno = 'keno',
  FastGame = 'instant',
  Jackpot = 'jackpots',
  Favorite = 'favorite',
  CockFight = 'cock_fight',
  Casino = 'casino',
}

export enum GamePartnerKeyEnum {
  CardGame = 'game_cards',
  Slots = 'slot',
  NoHu = 'nohu',
  Fishing = 'fishing',
  TableGame = 'table_game',
  NumberGame = 'lottery',
  Lottery = 'lo_de',
  Keno = 'keno',
  FastGame = 'quick_game',
  Jackpot = 'jackpots',
  Favorite = 'favorite',
  CockFight = 'cock_fight',
}

export enum GameSortEnum {
  All = 'all',
  Recent = 'recent',
  Favorite = 'favorite',
  Hot = 'hot',
  Recommended = 'recommended',
  Top = 'top',
}

export enum GameProviderEnum {
  PGSoft = 'pgsoft',
  RedTiger = 'redtiger',
  Spribe = 'spribe',
  Microgaming = 'microgaming',
  ApPlay = 'ap-play',
  Pragmatic = 'pragmatic',
  PlayNGo = 'play-ngo',
  Hananero = 'hananero',
  Saba = 'saba',
  HoGaming = 'hogaming',
  Sagaming = 'sagaming',
  DreamGaming = 'dreamgaming',
  KingMakerFull = 'kingmaker',
  KSport = 'k-sport',
  AskMe = 'askme',
  Go88 = 'go88',
  FCChai = 'fc-chai',
  BTI = 'bti',
  Esport = 'esport',
  Betradar = 'betradar',
  JDB = 'jdb',
  Netent = 'netent',
  AskMeBet = 'askmebet',
  Go = 'go',
  Evolution = 'evo',
  QTech = 'qtech',
  Mg = 'mg',
  CCGames = 'cc-games',
  CQ9 = 'cq9',
  InPlay = 'in_play',
  DigMaan = 'digmaan',
  IM = 'im',
  Ebet = 'ebet',
  Evoplay = 'evoplay',
  Ezugi = 'ezugi',
  GMW = 'gmw',
  Hacksaw = 'hacksaw',
  AskMeLotto = 'askmelotto',
  IBC = 'ibc',
  Jili = 'jili',
  Vingame = 'vingame',
  Livespin = 'livespin',
  MSport = 'm-sport',
  NoLimit = 'nolimit',
  OGame = 'ogame',
  Playtech = 'playtech',
  Relax = 'relax',
  Vivo = 'vivo',
  JDBGaming = 'jdb-gaming',
  TechPlay = 'techplay',
  Sungame = 'sungame',
  Game789 = '789game',
  Rik = 'rik',
  B52 = 'b52',
}

export enum GameProviderNameEnum {
  TechPlay = 'Techplay',
  PGSoft = 'PG Soft',
  IM = 'IM',
  JDB = 'JDB Gaming',
  Netent = 'Netent',
  AskMeLotto = 'AskMeLotto',
  AskMeBet = 'Ask Me Bet',
  Go88 = 'Go88',
  Evolution = 'Evolution',
  RedTiger = 'Red Tiger',
  QTech = 'QTech',
  Microgaming = 'Microgaming',
  Pragmatic = 'Pragmatic',
  Game789 = '789club',
  Sungame = 'sunwin',
}

export enum CasinoCategoryEnum {
  All = 'all',
  Blackjack = 'blackjack',
  XocDia = 'xocdia',
  Roulette = 'roulette',
  Poker = 'poker',
  RongHo = 'dragon_tiger',
  Baccarat = 'baccarat',
  TaiXiu = 'sicbo',
  BauCua = 'baucua',
  Other = 'other',
}

export enum CasinoLobbyKeyEnum {
  All = 'all',
  Blackjack = 'blackjack',
  XocDia = 'xoc-dia',
  Roulette = 'roulette',
  Poker = 'poker',
  RongHo = 'rong-ho',
  Baccarat = 'baccarat',
  TaiXiu = 'tai-xiu',
  BauCua = 'bau-cua',
  Other = 'other',
}

export enum LobbyTypeEnum {
  GAME = 'GAME',
  CASINO = 'CASINO',
  ALL = 'ALL',
}

export enum LiveStreamEnum {
  RikVgmn108 = 'rik_vgmn_108',
  RikVgmn109 = 'rik_vgmn_109',
  RikVgmn110 = 'rik_vgmn_110',
  RikVgmn111 = 'rik_vgmn_111',
  GoQsTxgo101 = 'go_qs_txgo-101',
  GoVgmn109 = 'go_vgmn_109',
  B52Vgmn108 = 'b52_vgmn_108',
  B52Vgmn109 = 'b52_vgmn_109',
  B52Vgmn110 = 'b52_vgmn_110',
  Game789G1X305 = '789game_G1X_305',
  Game789G1X306 = '789game_G1X_306',
  Vgmn108 = 'vgmn_108',
  Vgmn109 = 'vgmn_109',
  Vgmn110 = 'vgmn_110',
  Vgmn111 = 'vgmn_111',
  QsTxgo101 = 'qs_txgo-101',
  QsXocdia102 = 'qs_xocdia-102',
  G1X305 = 'G1X_305',
  G1X306 = 'G1X_306',
  G1S305 = 'G1S_305',
  G1S306 = 'G1S_306',
  G1S311 = 'G1S_311',
  SungameG1S311 = 'sungame_G1S_311',
  SungameG1S305 = 'sungame_G1S_305',
  SungameG1S306 = 'sungame_G1S_306',
}

export enum GameApiUrlEnum {
  // Go Game URLs
  TaiXiuGo = '/gameUrl?p=go&gId=vgmn_100',
  XocDiaGo = '/gameUrl?p=go&gId=vgcg_9',
  BauCuaGo = '/gameUrl?p=go&gId=vgcg_14',

  // Vingame URLs
  BietDoiMyNu = '/gameUrl?p=vingame&gId=kts9996',
  AnKheTraVang = '/gameUrl?p=vingame&gId=kts9998',
  TuLinh = '/gameUrl?p=vingame&gId=kts9991',
  ThanhXaBachXa = '/gameUrl?p=vingame&gId=kts9994',
  TayDuThanKhi = '/gameUrl?p=vingame&gId=kts9995',
  CasinoRoyal = '/gameUrl?p=vingame&gId=kts9950',

  // Live Casino URLs
  XocDiaLiveGo = '/casinoUrl?p=go&gId=vgmn_109&gt=xocdia&tId=',
  TaiXiuLivestreamGo = '/casinoUrl?p=go&gId=qs_txgo-101&gt=sicbo&tId=',
  BauCuaSexyB52 = '/casinoUrl?p=b52&gId=vgmn_108&gt=baucua&tId=',
  TaixiuSexyB52 = '/casinoUrl?p=b52&gId=vgmn_110&gt=sicbo&tId=',
  SexyXocDiaB52 = '/casinoUrl?p=b52&gId=vgmn_109&gt=xocdia&tId=',
  XocDiaLiveRik = '/casinoUrl?p=rik&gId=vgmn_109&gt=xocdia&tId=',
  FantanLiveRik = '/casinoUrl?p=rik&gId=vgmn_111&gt=other&tId=',
  BauCuaLiveRik = '/casinoUrl?p=rik&gId=vgmn_108&gt=baucua&tId=',
  TaixiuXanhChinRik = '/casinoUrl?p=rik&gId=vgmn_110&gt=sicbo&tId=',
  // -------------------------------------------
  TaiXiuSun = '/casinoUrl?p=sungame&gId=G1S_305&gt=sicbo&tId=',
  XocDiaSun = '/casinoUrl?p=sungame&gId=G1S_306&gt=xocdia&tId=',
  TaiXiuSun2 = '/casinoUrl?p=sungame&gId=G1S_311&gt=taixiu&tId=',
  TaiXiu789 = '/casinoUrl?p=789game&gId=G1X_305&gt=sicbo&tId=',
  XocDia789 = '/casinoUrl?p=789game&gId=G1X_306&gt=xocdia&tId=',
}
