export enum ModalIdEnum {
  Register = 'register',
  Login = 'login',
  IncompleteRegister = 'incompleteRegister',
  MaintainGame = 'maintainGame',
  DenyGame = 'denyGame',
  ForgotPassword = 'forgotPassword',
  Search = 'search',
  PhoneCard = 'phoneCard',
  Logout = 'logout',
  AddBank = 'addBank',
  UsePromotion = 'usePromotion',
  VerifyEmail = 'verifyEmail',
  CancelPromotion = 'cancelPromotion',
  VerifyTelegram = 'verifyTelegram',
  DepositPromotion = 'depositPromotion',
  LotteryResult = 'lotteryResult',
  CancelDeposit = 'cancelDeposit',
  WithdrawCryptoChangeRate = 'withdrawCryptoChangeRate',
  WithdrawCryptoConfirm = 'withdrawCryptoConfirm',
  ErrorApi = 'errorApi',
  ErrorFavoriteGameLimit = 'errorFavoriteGameLimit',
  MaintainBank = 'maintainBank',
  GateGames = 'gateGames',
  ErrorCodepay = 'ErrorCodepay',
}
