export const MAPPING_BANK_CODE: Record<string, string> = {
  bvb: 'baovietbank',
  icb: 'vietinbank',
  msb: 'maritimebank',
  tcb: 'techcombank',
  vpb: 'vpbank',
  scb: 'sacombank',
  sab: 'sacombank',
  mb: 'mbbank',
  hdb: 'hdbank',
  nab: 'namabank',
  dab: 'donga',
  eab: 'donga',
  wrb: 'wb',
  pvcb: 'pvcombank',
  abb: 'abbank',
  vba: 'agribank',
  vccb: 'vietcapital',
  eib: 'eximbank',
};

export const BANK_CODE_LIST = [
  {
    smartpay_code: 'vcb',
    bank_code: 'VCB',
    bank_name: 'Vietcombank',
    status: 1,
    bank_code_codepay: 'VCB',
  },
  {
    smartpay_code: 'acb',
    bank_code: 'ACB',
    bank_name: 'ACB',
    status: 1,
    bank_code_codepay: 'ACB',
  },
  {
    smartpay_code: 'eab',
    bank_code: 'DongA',
    bank_name: 'Vikki Digital Bank',
    status: 1,
    bank_code_codepay: 'DOB',
  },
  {
    smartpay_code: 'eab',
    bank_code: 'DAB',
    bank_name: 'Vikki Digital Bank',
    status: 1,
    bank_code_codepay: 'DAB',
  },
  {
    smartpay_code: 'vtb',
    bank_code: 'VietinBank',
    bank_name: 'VietinBank',
    status: 1,
    bank_code_codepay: 'ICB',
  },
  {
    smartpay_code: 'bidv',
    bank_code: 'BIDV',
    bank_name: 'BIDV',
    status: 1,
    bank_code_codepay: 'BIDV',
  },
  {
    smartpay_code: 'sab',
    bank_code: 'Sacombank',
    bank_name: 'Sacombank',
    status: 1,
    bank_code_codepay: 'STB',
  },
  {
    smartpay_code: 'tcb',
    bank_code: 'Techcombank',
    bank_name: 'Techcombank',
    status: 1,
    bank_code_codepay: 'TCB',
  },
  {
    smartpay_code: 'mb',
    bank_code: 'MBbank',
    bank_name: 'MBbank',
    status: 1,
    bank_code_codepay: 'MB',
  },
  {
    smartpay_code: 'vccb',
    bank_code: 'VietCapital',
    bank_name: 'BVBank',
    status: 1,
    bank_code_codepay: 'VCCB',
  },
  {
    smartpay_code: 'tpbank',
    bank_code: 'TPbank',
    bank_name: 'TPbank',
    status: 1,
    bank_code_codepay: 'TPB',
  },
  {
    smartpay_code: 'eib',
    bank_code: 'Eximbank',
    bank_name: 'Eximbank',
    status: 1,
    bank_code_codepay: 'EIB',
  },
  {
    smartpay_code: 'vba',
    bank_code: 'Agribank',
    bank_name: 'Agribank',
    status: 1,
    bank_code_codepay: 'VBA',
  },
  {
    smartpay_code: 'msb',
    bank_code: 'Maritimebank',
    bank_name: 'Maritimebank',
    status: 1,
    bank_code_codepay: 'MSB',
  },
  {
    smartpay_code: 'shb',
    bank_code: 'SHB',
    bank_name: 'SHB',
    status: 1,
    bank_code_codepay: 'SHB',
  },
  {
    smartpay_code: 'vpb',
    bank_code: 'VPbank',
    bank_name: 'VPbank',
    status: 1,
    bank_code_codepay: 'VPB',
  },
  {
    smartpay_code: 'nab',
    bank_code: 'NamABank',
    bank_name: 'NamABank',
    status: 1,
    bank_code_codepay: 'NAB',
  },
  {
    smartpay_code: 'pvcb',
    bank_code: 'PVcombank',
    bank_name: 'PVcombank',
    status: 1,
    bank_code_codepay: 'PVcombank',
  },
  {
    smartpay_code: 'scb',
    bank_code: 'SCB',
    bank_name: 'SCB',
    status: 1,
    bank_code_codepay: 'SCB',
  },
  {
    smartpay_code: 'ocb',
    bank_code: 'OCB',
    bank_name: 'OCB',
    status: 1,
    bank_code_codepay: 'OCB',
  },
  {
    smartpay_code: 'bvb',
    bank_code: 'BAOVIETBANK',
    bank_name: 'BAOVIETBANK',
    status: 1,
    bank_code_codepay: 'BAOVIETBANK',
  },
  {
    smartpay_code: 'hdb',
    bank_code: 'HDBank',
    bank_name: 'HDBank',
    status: 1,
    bank_code_codepay: 'HDB',
  },
  {
    smartpay_code: 'lpb',
    bank_code: 'LPB',
    bank_name: 'LPB',
    status: 1,
    bank_code_codepay: 'LPB',
  },
  {
    smartpay_code: 'ncb',
    bank_code: 'NCB',
    bank_name: 'NCB',
    status: 1,
    bank_code_codepay: 'NCB',
  },
  {
    smartpay_code: 'shbvn',
    bank_code: 'SHBVN',
    bank_name: 'SHBVN',
    status: 1,
    bank_code_codepay: 'SHBVN',
  },
  {
    smartpay_code: 'seab',
    bank_code: 'SEAB',
    bank_name: 'SeaBank',
    status: 1,
    bank_code_codepay: 'SEAB',
  },
  {
    smartpay_code: 'scvn',
    bank_code: 'SCBL',
    bank_name: 'SCBL',
    status: 1,
    bank_code_codepay: 'SCVN',
  },
  {
    smartpay_code: 'klb',
    bank_code: 'KLB',
    bank_name: 'KLB',
    status: 1,
    bank_code_codepay: 'KLB',
  },
  {
    smartpay_code: 'wrb',
    bank_code: 'WB',
    bank_name: 'Woori Bank',
    status: 1,
    bank_code_codepay: 'WB',
  },
  {
    smartpay_code: 'abb',
    bank_code: 'ABbank',
    bank_name: 'ABbank',
    status: 1,
    bank_code_codepay: 'ABB',
  },
  {
    smartpay_code: 'vncb',
    bank_code: 'VNCB',
    bank_name: 'VNCB',
    status: 1,
    bank_code_codepay: 'VNCB',
  },
  {
    smartpay_code: 'ivb',
    bank_code: 'IVB',
    bank_name: 'IVB',
    status: 1,
    bank_code_codepay: 'IVB',
  },
  {
    smartpay_code: 'oceanbank',
    bank_code: 'OCEB',
    bank_name: 'OCEB',
    status: 1,
    bank_code_codepay: 'OCEB',
  },
  {
    smartpay_code: 'pgb',
    bank_code: 'PGB',
    bank_name: 'PGB',
    status: 1,
    bank_code_codepay: 'PGB',
  },
  {
    smartpay_code: 'sgicb',
    bank_code: 'SGB',
    bank_name: 'SGB',
    status: 1,
    bank_code_codepay: 'SGB',
  },
  {
    smartpay_code: 'vab',
    bank_code: 'VAB',
    bank_name: 'VAB',
    status: 1,
    bank_code_codepay: 'VAB',
  },
];
