import type {
  GamesType,
  HotGame,
  IFrameLinkSports,
  JackpotGameDefinition,
  LiveCasinoGame,
  LiveCasinoSmallThumb,
  TopWinnerType,
} from '@/types/game';
import {
  GameApiUrlEnum,
  GameProviderEnum,
  IframeLinkEnum,
  LiveStreamEnum,
  RouterPathEnum,
  TopWinnerEnum,
} from '@/enums';
import TaixiuB52Image from '@/public/images/home/live-casino/taixiu-b52.webp';

import XocDia789Image from '@/public/images/home/live-casino/xocdia-789.webp';
import XocDiaHitImage from '@/public/images/home/live-casino/xocdia-hit.webp';
import { HOT_GAME_IMAGES } from './images/hot-game';
import {
  LIVE_CASINO_SMALL_THUMB,
  LIVE_CASINO_SMALL_THUMB_MOBILE,
} from './images/live-casino';

export const LIMIT_HOT_GAMES = 42;
export const LIMIT_HOT_GAMES_MOBILE = 18;
export const LIMIT_JACKPOT_GAMES = 14;
export const LIMIT_JACKPOT_GAMES_MOBILE = 14;
export const LIMIT_NEWS = 4;

const gameNames = {
  tai_xiu: 'Tài xỉu',
  bau_cua: 'Bầu cua',
  xoc_dia: 'Xóc đĩa',
  fantan: 'Fantan',
};

export const LIVE_CASINO_GAMES: LiveCasinoGame[] = [
  {
    id: 1,
    api_url: GameApiUrlEnum.XocDiaLiveGo,
    title: gameNames.xoc_dia,
    icon: 'icon-provider-hit',
    img: XocDiaHitImage,
    imgMobile: XocDiaHitImage,
    partner_provider: GameProviderEnum.Go,
    partner_game_id: LiveStreamEnum.Vgmn109,
    isPlaying: false,
  },
  {
    id: 2,
    api_url: GameApiUrlEnum.XocDia789,
    title: gameNames.xoc_dia,
    icon: 'icon-provider-789',
    img: XocDia789Image,
    imgMobile: XocDia789Image,
    partner_provider: GameProviderEnum.Game789,
    partner_game_id: LiveStreamEnum.G1X306,
    isPlaying: false,
  },
  {
    id: 3,
    api_url: GameApiUrlEnum.TaixiuSexyB52,
    title: gameNames.tai_xiu,
    icon: 'icon-provider-b52',
    img: TaixiuB52Image,
    imgMobile: TaixiuB52Image,
    partner_provider: GameProviderEnum.B52,
    partner_game_id: LiveStreamEnum.B52Vgmn110,
    isPlaying: false,
  },
];

export const DATA_CASINO_KEY_MAP: [string, { id: string; key: string }][] = [
  [
    'rik_vgmn_108',
    { id: '41b93f00-3f85-4008-86e2-8e297e6799aa', key: 'XpjSI-uWCBa' },
  ],
  [
    'rik_vgmn_109',
    { id: '867f07d4-2a67-4aa0-9c9a-306489ac3ca5', key: 'XpjSI-Xl7Hj' },
  ],
  [
    'rik_vgmn_110',
    { id: 'dbfca645-f428-4157-858d-a52a7fd026e3', key: 'XpjSI-PkUx8' },
  ],
  [
    'rik_vgmn_111',
    { id: 'da3844de-812d-446d-b1e9-158eb10819c4', key: 'XpjSI-t7no7' },
  ],
  [
    'go_qs_txgo-101',
    { id: '360d8af8-5d64-43df-9bd9-fa91ad6f9c60', key: 'XpjSI-X3Chu' },
  ],
  [
    'go_vgmn_109',
    { id: '9291199a-50c5-434b-9e97-5aeb670927d1', key: 'XpjSI-MsM1Y' },
  ],
  [
    'b52_vgmn_108',
    { id: 'f61fbb0a-2595-450e-ae70-19b04bdc5710', key: 'XpjSI-5emz7' },
  ],
  [
    'b52_vgmn_109',
    { id: 'ff9599e8-8cc4-40a2-ae0a-6f6c43984ccc', key: 'XpjSI-vlkTG' },
  ],
  [
    'b52_vgmn_110',
    { id: '946b8871-2b8d-4dfd-9fe7-4ffd835fe98a', key: 'XpjSI-h2HI7' },
  ],
  [
    '789game_G1X_305',
    { id: 'f23545d4-bbb0-416f-bbb7-972619813f2c', key: '7MhcV-weX7L' },
  ],
  [
    '789game_G1X_306',
    { id: 'fd2186c3-26f3-40ac-9864-4287052b0ec3', key: '7MhcV-fwQ2N' },
  ],
  [
    'sungame_G1S_305',
    { id: '7652d5a1-11fd-4f52-bb74-933631fd78df', key: '7MhcV-Pi0uG' },
  ],
  [
    'sungame_G1S_306',
    { id: 'c88ff431-0ee8-4faf-b375-1b515b20ae68', key: '7MhcV-ZvYvo' },
  ],
  ['sungame_G1S_311', { id: 'G4BpH3', key: 'Da1Lws1aVDn3nsWStream2-1' }],
];

export const MILLI_CAST_PLAYER = [
  'homepage_sungame_G1S_311',
  'sungame_G1S_311',
  'casino_sungame_G1S_311',
];

export const VIRTUAL_SPORTS_GAMES = [
  {
    id: 1,
    href: IframeLinkEnum.SABA_VIRTUAL,
    imageSrc: '/images/sport/virtual-sport-1.webp',
    imageMobileSrc: '/images/sport/virtual-sport-mobile-1.webp',
    imageAlt: 'virtual-sport-1',
    label: 'Saba',
    tabImageSrc: '/images/sport/tabs/saba.webp',
    tabImageAlt: 'Saba',
  },
  {
    id: 2,
    href: IframeLinkEnum.KSPORT_VIRTUAL,
    imageSrc: '/images/sport/virtual-sport-2.webp',
    imageMobileSrc: '/images/sport/virtual-sport-mobile-2.webp',
    imageAlt: 'virtual-sport-2',
    label: 'K-sports',
    tabImageSrc: '/images/sport/tabs/ksports.webp',
    tabImageAlt: 'K-sports',
  },
  {
    id: 3,
    href: IframeLinkEnum.INPLAY,
    imageSrc: '/images/sport/virtual-sport-3.webp',
    imageMobileSrc: '/images/sport/virtual-sport-mobile-3.webp',
    imageAlt: 'virtual-sport-3',
    label: 'Im',
    tabImageSrc: '/images/sport/tabs/im.webp',
    tabImageAlt: 'Im',
  },
  {
    id: 4,
    href: IframeLinkEnum.PRAGMATIC_VIRTUAL,
    imageSrc: '/images/sport/virtual-sport-4.webp',
    imageMobileSrc: '/images/sport/virtual-sport-mobile-4.webp',
    imageAlt: 'virtual-sport-4',
    label: 'Pragmatic',
    tabImageSrc: '/images/sport/tabs/bti.webp',
    tabImageAlt: 'Pragmatic',
  },
];

export const ESPORTS_GAME = [
  {
    id: 'saba',
    link: IframeLinkEnum.SABA_E,
    img: '/images/sport/card-e-sport-1.webp',
    imgMobile: '/images/sport/card-e-sport-mobile-1.webp',
    tabImg: '/images/sport/tabs/saba.webp',
    title: 'Saba',
  },
  {
    id: 'im',
    link: IframeLinkEnum.IM_E,
    img: '/images/sport/card-e-sport-2.webp',
    imgMobile: '/images/sport/card-e-sport-mobile-2.webp',
    tabImg: '/images/sport/tabs/im.webp',
    title: 'Im',
  },
];

export const SPORT_GAMES: IFrameLinkSports[] = [
  {
    id: 1,
    href: IframeLinkEnum.OSPORT,
    img: '/images/sport/saba.webp',
    imgMobile: '/images/sport/saba-mobile.webp',
    imgTab: '/images/sport/tabs/saba.webp',
    name: 'saba',
  },
  {
    id: 2,
    href: IframeLinkEnum.KSport,
    img: '/images/sport/ksports.webp',
    imgMobile: '/images/sport/ksports-mobile.webp',
    imgTab: '/images/sport/tabs/ksports.webp',
    name: 'ksports',
  },
  {
    id: 3,
    href: IframeLinkEnum.IBC,
    img: '/images/sport/im.webp',
    imgMobile: '/images/sport/im-mobile.webp',
    imgTab: '/images/sport/tabs/im.webp',
    name: 'im',
  },
  {
    id: 4,
    href: IframeLinkEnum.BTI,
    img: '/images/sport/bti.webp',
    imgMobile: '/images/sport/bti-mobile.webp',
    imgTab: '/images/sport/tabs/bti.webp',
    name: 'bti',
  },
];

export const TOP_SPORTS: IFrameLinkSports[] = [
  {
    id: 1,
    href: IframeLinkEnum.OSPORT,
    img: '/images/sport/top-sport-1.webp',
    imgMobile: '/images/sport/top-sport-mobile-1.webp',
    imgTab: '/images/sport/tabs/saba.webp',
    name: 'saba',
  },
  {
    id: 2,
    href: IframeLinkEnum.KSport,
    img: '/images/sport/top-sport-2.webp',
    imgMobile: '/images/sport/top-sport-mobile-2.webp',
    imgTab: '/images/sport/tabs/ksports.webp',
    name: 'ksports',
  },
  {
    id: 3,
    href: IframeLinkEnum.IBC,
    img: '/images/sport/top-sport-3.webp',
    imgMobile: '/images/sport/top-sport-mobile-3.webp',
    imgTab: '/images/sport/tabs/im.webp',
    name: 'im',
  },
  {
    id: 4,
    href: IframeLinkEnum.BTI,
    img: '/images/sport/top-sport-4.webp',
    imgMobile: '/images/sport/top-sport-mobile-4.webp',
    imgTab: '/images/sport/tabs/bti.webp',
    name: 'bti',
  },
];

export const TOP_WINNER: TopWinnerType = {
  [TopWinnerEnum.Day]: [
    {
      username: 'truong***k',
      name: 'Justice Machine',
      winlost: 179170,
    },
    {
      username: 'phanm***y',
      name: 'Mini Poker',
      winlost: 125843,
    },
    {
      username: 'doan***9',
      name: 'Phi Công Tài Ba',
      winlost: 102809,
    },
    {
      username: 'dangn***l',
      name: 'Magic Gate',
      winlost: 82439,
    },
    {
      username: 'hoang***2',
      name: 'Zillard King',
      winlost: 64775,
    },
    {
      username: 'hoang***e',
      name: '1 Reel Reef',
      winlost: 59378,
    },
    {
      username: 'truong***h',
      name: 'Glowing Fruits',
      winlost: 57828,
    },
    {
      username: 'tranthih***f',
      name: 'XÓC ĐĨA',
      winlost: 57330,
    },
  ],
  [TopWinnerEnum.Week]: [
    {
      username: 'hoang***c',
      name: 'Queen Of Ice Expanded Edition',
      winlost: 441718,
    },
    {
      username: 'nguyent***0',
      name: 'Mậu Binh',
      winlost: 428663,
    },
    {
      username: 'dangn***q',
      name: 'Thả Bóng Ăn Tiền',
      winlost: 382603,
    },
    {
      username: 'phanm***w',
      name: 'Golden Temple',
      winlost: 360547,
    },
    {
      username: 'nguyen***0',
      name: 'Happy Scratch',
      winlost: 351117,
    },
    {
      username: 'tranthih***v',
      name: 'Reels of Rio',
      winlost: 342826,
    },
    {
      username: 'dangn***6',
      name: "Patrick's Collection 20 Lines",
      winlost: 322508,
    },
    {
      username: 'leth***2',
      name: 'Kitty Cash',
      winlost: 315716,
    },
  ],
  [TopWinnerEnum.Month]: [
    {
      username: 'hoang***6',
      name: 'Golden Piggy Bank - Bling Bling',
      winlost: 1914099,
    },
    {
      username: 'buitr***u',
      name: 'Golden Piggy Bank - Bling Bling',
      winlost: 1870682,
    },
    {
      username: 'lyv***d',
      name: "Patrick's Collection 30 Lines",
      winlost: 1553284,
    },
    {
      username: 'doan***3',
      name: "Patrick's Collection 40 Lines",
      winlost: 1526964,
    },
    {
      username: 'hoang***o',
      name: 'Book Of Piggy Bank',
      winlost: 1297381,
    },
    {
      username: 'nguyent***k',
      name: 'Phi Công Tài Ba',
      winlost: 1256995,
    },
    {
      username: 'hoang***d',
      name: "Patrick's Collection - 10 Lines",
      winlost: 1247588,
    },
    {
      username: 'nguyen***y',
      name: 'Tài Xỉu Xanh Chín Live',
      winlost: 992262,
    },
  ],
};

export const DEFAULT_GAME_RESPONSE: GamesType = {
  display_type: '',
  display_types: [],
  items: [],
  limit: 0,
  page: 0,
  total: 0,
  totalPage: 0,
};

export const CASINO_KEY = 'live_casino';

export const JACKPOT_GAME: JackpotGameDefinition[] = [
  {
    key: 1,
    name: 'Tài Xỉu',
    image: 'tai_xiu_go',
    partner_provider: 'go',
    partner_game_id: 'vgmn_100',
    partner: 'go',
    partner_txt: 'GO',
    display_types: [15, 17],
    api_url: '/gameUrl?p=go&gId=vgmn_100',
    lobby_url: '/game-bai?partner=go&type=sicbo',
    jackpot_trigger: 20000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    key: 2,
    name: 'Xóc Đĩa',
    image: 'xoc_dia_go',
    partner_provider: 'go',
    partner_game_id: 'vgcg_9',
    partner: 'go',
    partner_txt: 'GO',
    display_types: [5, 15, 17, 21],
    api_url: '/gameUrl?p=go&gId=vgcg_9',
    lobby_url: '/game-bai?partner=go&type=xocdia',
    jackpot_trigger: 20000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    key: 5,
    name: 'BẦU CUA',
    image: 'bau_cua_go',
    partner_provider: 'go',
    partner_game_id: 'vgcg_14',
    partner: 'go',
    partner_txt: 'GO',
    display_types: [15, 17, 21],
    api_url: '/gameUrl?p=go&gId=vgcg_14',
    lobby_url: '/game-bai?partner=go&type=baucua',
    jackpot_trigger: 3000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Biệt Đội Mỹ Nữ: 70.000.000.000
    key: 12,
    name: 'Biệt Đội Mỹ Nữ',
    image: 'biet_doi_my_nu',
    partner_provider: 'vingame',
    partner_game_id: 'kts9996',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9996',
    lobby_url: '/no-hu',
    jackpot_trigger: 70000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Ăn Khế Trả Vàng: 45.000.000.000
    key: 13,
    name: 'Ăn Khế Trả Vàng',
    image: 'an_khe_tra_vang',
    partner_provider: 'vingame',
    partner_game_id: 'kts9998',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9998',
    lobby_url: '/no-hu',
    jackpot_trigger: 45000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Tứ Linh: 27.000.000.000
    key: 14,
    name: 'Tứ Linh',
    image: 'tu_linh',
    partner_provider: 'vingame',
    partner_game_id: 'kts9991',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9991',
    lobby_url: '/no-hu',
    jackpot_trigger: 27000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Thanh Xà Bạch Xà: 20.000.000.000
    key: 15,
    name: 'Thanh xà bạch xà',
    image: 'thanh_xa_bach_xa',
    partner_provider: 'vingame',
    partner_game_id: 'kts9994',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9994',
    lobby_url: '/no-hu',
    jackpot_trigger: 20000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Tây Du Thần Khí: 15.000.000.000
    key: 16,
    name: 'Tây Du Thần Khí',
    image: 'tay_du_than_khi',
    partner_provider: 'vingame',
    partner_game_id: 'kts9995',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9995',
    lobby_url: '/no-hu',
    jackpot_trigger: 15000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // TechPlay - Casino Royal: 8.000.000.000
    key: 17,
    name: 'Casino royal',
    image: 'casino_royal',
    partner_provider: 'vingame',
    partner_game_id: 'kts9950',
    partner: 'vingame',
    partner_txt: 'Techplay',
    api_url: '/gameUrl?p=vingame&gId=kts9950',
    lobby_url: '/no-hu',
    jackpot_trigger: 8000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
  },
  {
    // Go88 - Xóc Đĩa Live: 7.000.000.000
    key: 4,
    partner: 'go',
    partner_txt: 'GO',
    partner_provider: 'go',
    partner_game_id: 'vgmn_109',
    name: 'Xóc Đĩa Live',
    partner_game_type: 'xocdia',
    api_url: '/casinoUrl?p=go&gId=vgmn_109&gt=xocdia&tId=',
    image: 'xoc_dia',
    lobby_url: `/casino?partner=go&type=xocdia`,
    jackpot_trigger: 10000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
  {
    // Go88 - Tài Xỉu Live: 3.000.000.000
    key: 3,
    partner: 'go',
    partner_txt: 'GO',
    partner_provider: 'go',
    partner_game_id: 'qs_txgo-101',
    name: 'Tài Xỉu Livestream',
    partner_game_type: 'sicbo',
    api_url: '/casinoUrl?p=go&gId=qs_txgo-101&gt=sicbo&tId=',
    image: 'tai_xiu_livestream',
    lobby_url: `/casino?partner=go&type=sicbo`,
    jackpot_trigger: 5000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
  {
    // B52 -Bầu cua Sexy: 1.500.000.000
    key: 8,
    partner: 'b52',
    partner_txt: 'B52',
    partner_provider: 'b52',
    partner_game_id: 'b52_vgmn_108',
    name: 'Bầu Cua Sexy',
    partner_game_type: 'baucua',
    api_url: '/casinoUrl?p=b52&gId=vgmn_108&gt=baucua&tId=',
    image: 'bau_cua_sexy',
    lobby_url: `/casino?partner=b52&type=baucua`,
    jackpot_trigger: 1500000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
  {
    // RikVip - Sóc đĩa Live: 1.000.000.000
    key: 9,
    partner: 'rik',
    partner_txt: 'RIK',
    partner_provider: 'rik',
    partner_game_id: 'rik_vgmn_109',
    name: 'Xóc Đĩa Live',
    partner_game_type: 'xocdia',
    api_url: '/casinoUrl?p=rik&gId=vgmn_109&gt=xocdia&tId=',
    image: 'xoc_dia_live_rik',
    lobby_url: `/casino?partner=rik&type=xocdia`,
    jackpot_trigger: 1000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
  {
    // RikVip - Fantan Live: 1.000.000.000
    key: 10,
    partner: 'rik',
    partner_txt: 'RIK',
    partner_provider: 'rik',
    partner_game_id: 'rik_vgmn_111',
    name: 'Fantan Live',
    partner_game_type: 'other',
    api_url: '/casinoUrl?p=rik&gId=vgmn_111&gt=other&tId=',
    image: 'fanta_live',
    lobby_url: `/casino?partner=rik&type=other`,
    jackpot_trigger: 1000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
  {
    // RikVIP - Bầu Cua Live: 1.000.000.000
    key: 11,
    partner: 'rik',
    partner_txt: 'RIK',
    partner_provider: 'rik',
    partner_game_id: 'rik_vgmn_108',
    name: 'Bầu Cua Live',
    partner_game_type: 'baucua',
    api_url: '/casinoUrl?p=rik&gId=vgmn_108&gt=baucua&tId=',
    image: 'bau_cua_live',
    lobby_url: `/casino?partner=rik&type=baucua`,
    jackpot_trigger: 1000000000,
    jackpot_value: 0,
    is_valid: false,
    is_jackpot_event: true,
    is_live_stream: true,
  },
];

export const HOT_GAME_LIST: HotGame[] = [
  {
    id: 1,
    img: HOT_GAME_IMAGES.LiveCasino,
    imgMb: HOT_GAME_IMAGES.LiveCasino,
    title: 'Live Casino',
    isThumbnail: true,
    orderOnPc: 1,
    orderOnMb: 2,
    href: RouterPathEnum.LiveCasino,
  },
  {
    id: 2,
    img: HOT_GAME_IMAGES.Sport,
    imgMb: HOT_GAME_IMAGES.Sport,
    title: 'Sport',
    isThumbnail: true,
    orderOnPc: 6,
    orderOnMb: 1,
    href: RouterPathEnum.Sports,
  },
  {
    id: 3,
    img: HOT_GAME_IMAGES.Jackpot,
    imgMb: HOT_GAME_IMAGES.Jackpot,
    title: 'Jackpot',
    orderOnPc: 2,
    orderOnMb: 5,
    href: RouterPathEnum.Jackpot,
  },
  {
    id: 4,
    img: HOT_GAME_IMAGES.Volta,
    imgMb: HOT_GAME_IMAGES.Volta,
    title: 'Volta',
    orderOnPc: 3,
    orderOnMb: 6,
    href: IframeLinkEnum.Volta,
    requireLogin: true,
  },
  {
    id: 10,
    img: HOT_GAME_IMAGES.Fishing,
    imgMb: HOT_GAME_IMAGES.Fishing,
    title: 'Fishing',
    orderOnPc: 4,
    orderOnMb: 7,
    href: RouterPathEnum.Fishing,
  },
  {
    id: 5,
    img: HOT_GAME_IMAGES.Card,
    imgMb: HOT_GAME_IMAGES.Card,
    title: 'Card',
    orderOnPc: 5,
    orderOnMb: 8,
    href: RouterPathEnum.GameBai,
  },
  {
    id: 6,
    img: HOT_GAME_IMAGES.ESports,
    imgMb: HOT_GAME_IMAGES.ESports,
    title: 'ESports',
    orderOnPc: 7,
    orderOnMb: 3,
    href: RouterPathEnum.ESport,
  },
  {
    id: 7,
    img: HOT_GAME_IMAGES.VirtualSports,
    imgMb: HOT_GAME_IMAGES.VirtualSports,
    title: 'Virtual Sports',
    orderOnPc: 8,
    orderOnMb: 4,
    href: RouterPathEnum.VirtualSport,
  },
  {
    id: 8,
    img: HOT_GAME_IMAGES.Lottery,
    imgMb: HOT_GAME_IMAGES.Lottery,
    title: 'Lottery',
    orderOnPc: 9,
    orderOnMb: 9,
    href: RouterPathEnum.Lottery,
  },
  {
    id: 9,
    img: HOT_GAME_IMAGES.QuaySo,
    imgMb: HOT_GAME_IMAGES.QuaySo,
    title: 'Quay Số',
    orderOnPc: 10,
    orderOnMb: 10,
    href: RouterPathEnum.QuaySo,
  },
];

export const LIVE_CASINO_GAME_LIST: LiveCasinoSmallThumb[] = [
  {
    id: 1,
    img: LIVE_CASINO_SMALL_THUMB.SunWin!,
    imgMb: LIVE_CASINO_SMALL_THUMB_MOBILE.SunWin!,
    provider: GameProviderEnum.Sungame,
    partner_provider: GameProviderEnum.Sungame,
    partner_game_id: LiveStreamEnum.G1S305,
    href: `${RouterPathEnum.LiveCasino}?partner=sungame`,
  },
  {
    id: 5,
    img: LIVE_CASINO_SMALL_THUMB.Go88!,
    imgMb: LIVE_CASINO_SMALL_THUMB_MOBILE.Go88!,
    provider: GameProviderEnum.Go88,
    partner_provider: GameProviderEnum.Go,
    partner_game_id: LiveStreamEnum.QsTxgo101,
    href: `${RouterPathEnum.LiveCasino}?partner=go`,
  },
  {
    id: 2,
    img: LIVE_CASINO_SMALL_THUMB.B52!,
    imgMb: LIVE_CASINO_SMALL_THUMB_MOBILE.B52!,
    provider: GameProviderEnum.B52,
    partner_provider: GameProviderEnum.B52,
    partner_game_id: LiveStreamEnum.Vgmn108,
    href: `${RouterPathEnum.LiveCasino}?partner=b52`,
  },
  {
    id: 3,
    img: LIVE_CASINO_SMALL_THUMB.RikVip!,
    imgMb: LIVE_CASINO_SMALL_THUMB_MOBILE.RikVip!,
    provider: GameProviderEnum.Rik,
    partner_provider: GameProviderEnum.Rik,
    partner_game_id: LiveStreamEnum.Vgmn111,
    href: `${RouterPathEnum.LiveCasino}?partner=rik`,
  },
  {
    id: 4,
    img: LIVE_CASINO_SMALL_THUMB.Seven89Club!,
    imgMb: LIVE_CASINO_SMALL_THUMB_MOBILE.Seven89Club!,
    provider: GameProviderEnum.Game789,
    partner_provider: GameProviderEnum.Game789,
    partner_game_id: LiveStreamEnum.G1X305,
    href: `${RouterPathEnum.LiveCasino}?partner=789game`,
  },
];
