name: Dependency Scan on Push
on:
  push:
    branches:
      - main
permissions:
  contents: read # Quyền tối thiểu để đọc nội dung repository
  # Nếu cần quyền khác, thêm vào đây (ví dụ: issues: write, pull-requests: write)
jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run dependency vulnerability scan
        run: npm audit --json | tee audit-report.json
      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: audit-report
          path: audit-report.json
      - name: Fail if vulnerabilities are found
        run: |
          if [ $(jq '.metadata.vulnerabilities.total' audit-report.json) -gt 0 ]; then
            echo "Vulnerabilities found! Check the audit report."
            exit 1
          fi
